### ISSUE TITLE
Completion kind types symbol

### ISSUE THREAD

**Issue by yashLadha** [nvim-lua/completion-nvim#298]
**Is your feature request related to a problem? Please describe.**
I want to basically have a custom symbol based on the completion type in the pmenu, something like this https://github.com/neoclide/coc.nvim/pull/603 . Can this configuration achievable in the current setup?

**Describe the solution you'd like**
Having control it through a mapping like `let g:completion_kind_overrides`.

**Describe alternatives you've considered**

**Comment by clason** [comment]
@yashLadha That was already discussed (and partially implemented) in https://github.com/nvim-lua/completion-nvim/issues/36, see https://github.com/nvim-lua/completion-nvim/issues/36#issuecomment-617329770

But it's actually not necessary to support this in `completion-nvim` since that's already really easy with core LSP functionality: https://github.com/nvim-lua/completion-nvim/wiki/Customizing-LSP-label

**Comment by yashLadha** [comment]
Yes thanks for sharing the resource. Would be nice to have it in the README under customization.
