### ISSUE TITLE
Clangd Snippets not working properly

### ISSUE THREAD

**Issue by saadparwaiz1** [nvim-lua/completion-nvim#324]
- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
Post your init.vim to help me reproduce this issue
```
let g:completion_enable_snippet = 'snippets.nvim'
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
require('lspconfig').clangd.setup {
  on_attach = require 'completion'.on_attach,
 capabilities = capabilities
}
```

**How to reproduce**
Open up a C file and try to use one of the macro snippets as follows:
https://user-images.githubusercontent.com/73385353/104222673-88822900-543a-11eb-9004-e98899862b02.mov

**Expected behaviour**
Proper snippet completion

**Comment by saadparwaiz1** [comment]
I went through the source code, and the problem apparently arises if the matching strategy doesn't contain 'substring'. If we include substring the problem fixes itself. However, the snippets still don't work as expected as they add an extra angled bracket '>' at the end and a space at the start

**Comment by saadparwaiz1** [comment]
here's a video of the problem described:

https://user-images.githubusercontent.com/73385353/104237042-60e98b80-544f-11eb-9689-e3ef8776f25a.mov

**Comment by haorenW1025** [comment]
The snippets expansion is not properly done on `completion-nvim` since the main goal of this plugins is to do completion but not snippets expansion. Maybe I'll make it far better when I have some spare time but that's not the priority for now. My suggestion is using `vim-vsnip` and `vim-vsnip-integ` along side with `completion-nvim`. The snippets expansion is far better on their side and it doesn't require any extra setup cause `completion-nvim` calls the api automatically on `CompleteDone` autocmd. You don't have to use `substring` completion too if you used `vim-vsnip` and `vim-vsnip-integ`.

**Comment by saadparwaiz1** [comment]
Thank you for the reply!
